# Generated by Django 3.0.1 on 2020-02-28 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_text', models.CharField(max_length=500)),
                ('back_text', models.CharField(max_length=500)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.CardBundle')),
            ],
        ),
    ]
